{% set name = "typos-cli" %}
{% set version = "1.27.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/crate-ci/typos/archive/v{{ version }}.tar.gz
  sha256: 21d0fedc66be2efdad8db0741f27b831728e0cfd5cedd9bdf1076f9e71da0aa4

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - typos --help

about:
  home: https://github.com/crate-ci/typos-cli
  license: Apache-2.0 AND MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Source code spell checker
  dev_url: https://github.com/crate-ci/typos-cli

extra:
  recipe-maintainers:
    - danielnachun
