{% set name = "typos-cli" %}
{% set version = "1.40.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/crate-ci/typos/archive/v{{ version }}.tar.gz
  sha256: f8317b77e124f0201a47289a1d3e7a196e93cdbec3df9a0fc82d10c934c0ca85

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - typos --help

about:
  home: https://github.com/crate-ci/typos-cli
  license: Apache-2.0 AND MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Source code spell checker
  dev_url: https://github.com/crate-ci/typos-cli

extra:
  recipe-maintainers:
    - danielnachun
