{% set name = "typos-cli" %}
{% set version = "1.35.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/crate-ci/typos/archive/v{{ version }}.tar.gz
  sha256: 727289d71177fa6f15939d0c735ba116784e2ff7d8db20a97290d3b1622c86e2

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - typos --help

about:
  home: https://github.com/crate-ci/typos-cli
  license: Apache-2.0 AND MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Source code spell checker
  dev_url: https://github.com/crate-ci/typos-cli

extra:
  recipe-maintainers:
    - danielnachun
