schema_version: 1

context:
  version: "1.50.0"

package:
  name: typos-cli
  version: ${{ version }}

source:
  url: https://github.com/crate-ci/typos/archive/v${{ version }}.tar.gz
  sha256: 00bb5b96e4c7f8a652ab26f2bec3f9babf40efd3260ed3cebac6737e5de5171c

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - typos --help

about:
  license: Apache-2.0 AND MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Source code spell checker
  homepage: https://github.com/crate-ci/typos-cli
  repository: https://github.com/crate-ci/typos-cli

extra:
  recipe-maintainers:
    - danielnachun
