schema_version: 1

context:
  version: "1.47.1"

package:
  name: typos-cli
  version: ${{ version }}

source:
  url: https://github.com/crate-ci/typos/archive/v${{ version }}.tar.gz
  sha256: bc7bdeff13c8410a59bafc0705868e7e6bfd8a97525dc08b94d7879514beea3d

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - typos --help

about:
  license: Apache-2.0 AND MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Source code spell checker
  homepage: https://github.com/crate-ci/typos-cli
  repository: https://github.com/crate-ci/typos-cli

extra:
  recipe-maintainers:
    - danielnachun
