schema_version: 1

context:
  version: "1.43.1"

package:
  name: typos-cli
  version: ${{ version }}

source:
  url: https://github.com/crate-ci/typos/archive/v${{ version }}.tar.gz
  sha256: 34d738a30f5c46b14e3d963475ca1b16933b4cd61a352a17c63aae82f3160ed1

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - typos --help

about:
  license: Apache-2.0 AND MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Source code spell checker
  homepage: https://github.com/crate-ci/typos-cli
  repository: https://github.com/crate-ci/typos-cli

extra:
  recipe-maintainers:
    - danielnachun
