schema_version: 1

context:
  version: "1.50.2"

package:
  name: typos-cli
  version: ${{ version }}

source:
  url: https://github.com/crate-ci/typos/archive/v${{ version }}.tar.gz
  sha256: 412b161d33996e2c3c4a8b076e22183527f3420242975e868ba9968a3ce1727e

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - typos --help

about:
  license: Apache-2.0 AND MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Source code spell checker
  homepage: https://github.com/crate-ci/typos-cli
  repository: https://github.com/crate-ci/typos-cli

extra:
  recipe-maintainers:
    - danielnachun
